### ISSUE TITLE
no need

### ISSUE THREAD

**Issue by Shluffy** [Scratch-Bookmarklets/Scratch-Console-Extensions#1]
no need - if anything it should be the other way. Shall we delete this?

**Comment by gosoccerboy5** [comment]
I'd be fine

**Comment by ZI-Youtuber** [comment]
@Shluffy it is best to keep a seperate repo for the javascript code and as backup

**Comment by Shluffy** [comment]
> @Shluffy it is best to keep a seperate repo for the javascript code and as backup

i have a fork, i think @gosoccerboy5 does too.

**Comment by ZI-Youtuber** [comment]
@Shluffy Well no problem with another backup right?

**Comment by gosoccerboy5** [comment]
> @Shluffy it is best to keep a seperate repo for the javascript code and as backup

Why would we need a backup? That's what git is for.

**Comment by ZI-Youtuber** [comment]
@Shluffy @gosoccerboy5 Well there's no problem though is there?

**Comment by gosoccerboy5** [comment]
Why does this have to be closed? It still counts as ongoing discussion no?

**Comment by ZI-Youtuber** [comment]
@gosoccerboy5 no
